apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
  namespace: misc
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: misc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: <PROVISIONER_NAME>
            - name: NFS_SERVER
              value: <NFS-SERVICE-IP>
            - name: NFS_PATH
              value: <EXPORT-PATH>
      volumes:
        - name: nfs-client-root
          nfs:
            server: <NFS-SERVER-IP>
            path: <EXPORT-PATH>
